# Uncomment this line to define a global platform for your project
platform :ios, '8.0'

target 'VulcanSample' do
  use_frameworks!
  pod 'Vulcan', :path => './../../'

  target 'VulcanSampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
